# Generated by Django 2.2.5 on 2019-10-15 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garlic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporter', models.CharField(help_text='Supporter Name.', max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garlic.Item')),
            ],
        ),
    ]
