# Generated by Django 2.2.5 on 2019-10-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garlic', '0003_auto_20191014_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='nicole.woodland@outlook.com', max_length=254),
            preserve_default=False,
        ),
    ]
