# Generated by Django 2.2.5 on 2019-10-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garlic', '0005_auto_20191014_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
