# Generated by Django 2.2.5 on 2019-10-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garlic', '0006_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
