# Generated by Django 2.2.5 on 2019-10-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garlic', '0007_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='item',
        ),
    ]
