# Generated by Django 2.2.5 on 2019-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garlic', '0010_auto_20191015_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=4),
        ),
    ]
